services:
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_MYSQL_PORT:-3399}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'chat-mysql:/var/lib/mysql'
    networks:
      - chat
  web:
    build: .
    ports:
      - "${SERVER_PORT:-8099}:8080"
    volumes:
      - ".:/app"
    depends_on:
      - db
    networks:
      - chat
    links:
      - "db:database"
networks:
  chat:
    driver: bridge
volumes:
  chat-mysql:
    driver: local
