version: '3'
services:
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
  web:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"

